# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - npm install
  - (cd themes/even; git apply ../../theme.patch; cp ../../list.algolia.json layouts/_default/; yarn install; yarn build)
  - ./hugo
  # ALGOLIA_ADMIN_KEY Set in travis-ci.org dashboard
  - npm run algolia

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: edward852/edward852.github.com
  target_branch: master
  on:
    branch: master
