# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: blog CI

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: sudo apt-get install -y python-pygments
    - run: rm -rf public || exit 0
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: (cd themes/even; git apply ../../theme.patch; yarn install; yarn build)
    - run: ./hugo
    # ALGOLIA_ADMIN_KEY Set in travis-ci.org dashboard
    - run: npm run algolia
