# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: blog CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        persist-credentials: false
    
    # node setup
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    # build the website
    #- run: git config core.quotepath false
    #- run: rm -rf public || exit 0
    - run: (cd themes/even; git apply ../../theme.patch)
    - run: ./hugo
    - run: npm install
    - run: npm run algolia
      env: 
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: edward852/edward852.github.com
        BRANCH: master
        FOLDER: public
        SINGLE_COMMIT: true
        CLEAN: false

